# These are supported funding model platforms

# GitHub Sponsors
github: [colleenpridemore]

# Uncomment and add other platforms as needed:
# patreon: username
# ko_fi: username
# custom: ["https://www.paypal.me/username", "https://example.com"]
